USE GD1C2024
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'SQLOVERS')
BEGIN 
	EXEC ('CREATE SCHEMA SQLOVERS')
END
GO

DROP TABLE SQLOVERS.DescuentosMedioPago_X_Pago
DROP TABLE SQLOVERS.Envio
DROP TABLE SQLOVERS.Descuento_Medio_Pago
DROP TABLE SQLOVERS.Promocion_x_ItemProducto
DROP TABLE SQLOVERS.ItemProducto
DROP TABLE SQLOVERS.Ticket
DROP TABLE SQLOVERS.Pago
DROP TABLE SQLOVERS.Medio_Pago
DROP TABLE SQLOVERS.Detalle_Pago
DROP TABLE SQLOVERS.Cliente
DROP TABLE SQLOVERS.Caja
DROP TABLE SQLOVERS.Promocion_Producto
DROP TABLE SQLOVERS.Producto
DROP TABLE SQLOVERS.Empleado
DROP TABLE SQLOVERS.Sucursal
DROP TABLE SQLOVERS.Supermercado
DROP TABLE SQLOVERS.Localidad
DROP TABLE SQLOVERS.Provincia
DROP TABLE SQLOVERS.Regla
DROP TABLE SQLOVERS.Tipo_Medio_Pago
DROP TABLE SQLOVERS.TipoCaja
DROP TABLE SQLOVERS.Marca_Producto
DROP TABLE SQLOVERS.Categoria
DROP TABLE SQLOVERS.EstadoEnvio
