SELECT 
PAGO_IMPORTE,
TICKET_TOTAL_DESCUENTO_APLICADO, 
TICKET_TOTAL_DESCUENTO_APLICADO_MP, 
PAGO_DESCUENTO_APLICADO,
(TICKET_SUBTOTAL_PRODUCTOS - TICKET_TOTAL_DESCUENTO_APLICADO - TICKET_TOTAL_DESCUENTO_APLICADO_MP - TICKET_TOTAL_ENVIO) AS RESUL,
TICKET_TOTAL_TICKET, 
TICKET_TOTAL_ENVIO, 
TICKET_SUBTOTAL_PRODUCTOS
FROM gd_esquema.Maestra 
WHERE PAGO_DESCUENTO_APLICADO IS NOT NULL


SELECT PAGO_MEDIO_PAGO, PAGO_TIPO_MEDIO_PAGO FROM gd_esquema.Maestra


SELECT 
    DESCUENTO_CODIGO, 
    DESCUENTO_DESCRIPCION
FROM
    gd_esquema.Maestra
WHERE DESCUENTO_CODIGO IS NOT NULL


SELECT * FROM SQLOVERS.Producto


SELECT id_localidad FROM Localidad WHERE nombre_localidad = gd_esquema.Maestra.CLIENTE_LOCALIDAD