SELECT 
PAGO_IMPORTE,
TICKET_TOTAL_DESCUENTO_APLICADO, 
TICKET_TOTAL_DESCUENTO_APLICADO_MP, 
PAGO_DESCUENTO_APLICADO,
(TICKET_SUBTOTAL_PRODUCTOS - TICKET_TOTAL_DESCUENTO_APLICADO - TICKET_TOTAL_DESCUENTO_APLICADO_MP - TICKET_TOTAL_ENVIO) AS RESUL,
TICKET_TOTAL_TICKET, 
TICKET_TOTAL_ENVIO, 
TICKET_SUBTOTAL_PRODUCTOS
FROM gd_esquema.Maestra 
WHERE PAGO_DESCUENTO_APLICADO IS NOT NULL


SELECT PAGO_MEDIO_PAGO, PAGO_TIPO_MEDIO_PAGO FROM gd_esquema.Maestra


SELECT 
    DESCUENTO_CODIGO, 
    DESCUENTO_DESCRIPCION
FROM
    gd_esquema.Maestra
WHERE DESCUENTO_CODIGO IS NOT NULL


SELECT * FROM SQLOVERS.Producto


SELECT DISTINCT 
    CLIENTE_NOMBRE, 
    CLIENTE_APELLIDO,
    CLIENTE_DNI,
    CLIENTE_FECHA_REGISTRO,
    CLIENTE_TELEFONO,
    CLIENTE_MAIL,
    CLIENTE_FECHA_NACIMIENTO,
    CLIENTE_DOMICILIO,
    (SELECT id_localidad FROM Localidad WHERE nombre_localidad = CLIENTE_LOCALIDAD)
FROM gd_esquema.Maestra;



SELECT DISTINCT 
    m.CLIENTE_NOMBRE, 
    m.CLIENTE_APELLIDO,
    m.CLIENTE_DNI,
    m.CLIENTE_FECHA_REGISTRO,
    m.CLIENTE_TELEFONO,
    m.CLIENTE_MAIL,
    m.CLIENTE_FECHA_NACIMIENTO,
    m.CLIENTE_DOMICILIO,
    l.id_localidad
FROM gd_esquema.Maestra m
LEFT JOIN Localidad l ON l.nombre_localidad = m.CLIENTE_LOCALIDAD;